### PR TITLE
Document simulated device and reader interaction for all states and transitions

### PR DESCRIPTION
**Pull request by radumarias**
Documented these members:
- `presentation::*`
- `presentation::device::*`
- `presentation::reader::*`
- some from `definitions::device_response`

CI:
- Run `cargo doc` in `ci` to catch warning for `rustdoc`
- Add `workflow_dispatch` so we can manually run on any branch, useful for PR that are to other branches than `main`

### CODE REVIEW

**Comment by radumarias** [comment]
@cobward if you can please review this.

**Comment by cobward** [comment]
@radumarias could you change the target of this PR to `spruceid/isomdl:main`, or raise a new PR to there?

**Comment by radumarias** [comment]
let me try that, I didn't do it because it's created from https://github.com/radumarias/isomdl/pull/1 which is not yet in parent `main`.

**Comment by radumarias** [comment]
@cobward created PR to parent https://github.com/spruceid/isomdl/pull/90

**Pull request closed without merging**
